worker_processes auto;
events { worker_connections 1024; }
http {
    server {
        listen 80;
        location / {
            # 直接返回 200 状态码和文本内容
            default_type text/html;
            return 200 "<h1>Hello, Nginx on Alpine!</h1>";
        }
    }
}