worker_processes auto;
events { }
http {
    # 加载MIME类型，确保浏览器正确识别文件
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name www.hetou.vip;
        
        # 容器内的网页根目录，和Dockerfile COPY的目标一致
        root /usr/share/nginx/html; 

        # 默认首页
        index index.html index.htm;

        # location / {
        #     # 直接返回 200 状态码和文本内容
        #     default_type text/html;
        #     return 200 "<h1>Hello, Nginx on Alpine!</h1>";
        # }
    }
}