services:
  server:
    build:
      context: ./server
    container_name: step4-proxy-server
    expose:
      - "4000"

  nginx:
    build:
      context: ./nginx
    container_name: step4-proxy-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
