services:
  nginx:
    build:
      context: ./nginx
    container_name: step7-redis-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: step7-redis-server
    expose:
      - "4000"
    env_file:
      - ./server/.env.prod


  mysql:
    image: mysql:8.0
    container_name: step7-redis-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"

  redis:
    image: redis:7.0-alpine
    container_name: step7-redis-redis
    ports:
      - "6379:6379"